#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C)  TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

####################################################################################################
# VARIABLES
####################################################################################################
[ ! -f "$TLAUNCH_FILE" ] && { echo "No menu file informed!"; exit 1; }
TYAML_COMMAND="tyaml $TLAUNCH_FILE"
menu_prompt=$($TYAML_COMMAND -k)
current_path=$menu_prompt
menu_utility=dmenu
menu_utility_arguments=""
version=0.4.0
extended=false

CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/tlaunch_cache
if [ ! -d "$(dirname "$CACHE")" ]; then
    CACHE=$HOME/.tlaunch_cache
fi
(
	IFS=:
	if stest -dqr -n "$CACHE" "$PATH"; then
		stest -flx "$PATH" | sort -u > "$CACHE"
	fi
)
####################################################################################################
# Functions
####################################################################################################

check_sub_item()
{
  selected_tag="$1"
  current_path+=".$selected_tag"

  sub_item="$($TYAML_COMMAND -k "$current_path")"

  if [[ -z "$sub_item" ]];
  then
    command="$($TYAML_COMMAND -v "$current_path")"
    if [ -z "$command" ] && [ -n "$selected_tag" ]; then
        echo "$selected_tag" | /bin/sh &
    elif [ "${command[*]}" != "null" ]; then
        echo "${command[*]}" | /bin/sh &
    fi
  else
    menu_prompt="$selected_tag"
    display_items
  fi
}

list_items()
{
    $TYAML_COMMAND -k "$current_path"
    ( $extended  && [ -f "$CACHE" ] && cat "$CACHE" )
}

display_items()
{

    tag_selected="$(list_items | $menu_utility -a "$menu_utility_arguments")"


  [ -z "$tag_selected" ] || check_sub_item "$tag_selected"
}

usage()
{
    echo "usage: tlaunch [-hve]"
    echo "e.g: export TLAUNCH_FILE=quick_menu.yaml; tlaunch"
    echo "options:"
    echo "-v: prints version information to stdout, then exits;"
    echo "-e: lists your menu file entries along with your binaries at your \$PATH variable;"
    echo "-h: shows this usage message."
}

parse_arguments()
{
    while getopts "hvefdxra:" args; do
        case "${args}" in
            h) usage; exit 0 ;;
            v) echo "$version"; exit 0 ;;
            f) menu_utility="tmenu -f" ;;
            d) menu_utility="tmenu -d" ;;
            x) menu_utility="tmenu -x" ;;
            r) menu_utility="tmenu -r" ;;
            a) menu_utility_arguments="${OPTARG}" ;;
            e) extended=true ;;
            *) usage; exit 1 ;;
        esac
    done
}

####################################################################################################
# Execute dmenu for the first time
####################################################################################################

parse_arguments "$@"
display_items
