#!/bin/sh

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C)  TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

####################################################################################################
# VARIABLES 
####################################################################################################
[ ! -f "$TMENU_FILE" ] && { echo "No menu file informed!"; exit 1; }
TYAML_COMMAND="tyaml $TMENU_FILE"
menu_prompt=$($TYAML_COMMAND -k)
current_path=$menu_prompt
CACHE=$HOME/.tmenu_cache

CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/tmenu_cache
if [ ! -d "`dirname "$CACHE"`" ]; then
	CACHE=$HOME/.dmenu_cache
fi
(
	IFS=:
	if stest -dqr -n "$CACHE" $PATH; then
		stest -flx $PATH | sort -u > "$CACHE"
	fi
)

####################################################################################################
# Functions
####################################################################################################

check_sub_item()
{
  selected_tag=$1
  current_path+=.$selected_tag

  sub_item=$($TYAML_COMMAND -k $current_path)

  if [ -z $sub_item ];
  then
    command=$($TYAML_COMMAND -v $current_path)
    if [ -z "$command" ] && [ ! -z "$selected_tag" ]; then
        echo "$selected_tag" | /bin/sh &
    elif [ "${command[@]}" != "null" ]; then
        echo "${command[@]}" | /bin/sh &
    fi
  else
    menu_prompt=$selected_tag
    display_items
  fi
}

list_items()
{
    $TYAML_COMMAND -k $current_path
    ( $extended  && [ -f "$CACHE" ] && cat "$CACHE" )
}

display_items()
{
  tag_selected=$(list_items | dmenu -p $menu_prompt)
  [ -z $tag_selected ] || check_sub_item $tag_selected
}

parse_arguments()
{
    while getopts "he" args; do
        case "${args}" in
            e) extended=true ;;
            h) echo "help";;
        esac
    done
}
####################################################################################################
# Execute dmenu for the first time
####################################################################################################

display_items
